language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.0.1
      env: build_config=Release
      env: netmoniker=net461
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.0.0
      env: build_config=Release
      env: netmoniker=net461
    - os: linux
      dist: precise
      sudo: required
      mono: 5.0.1
      env: build_config=Release
      env: netmoniker=net461
    - os: linux
      dist: precise
      sudo: required
      mono: 5.0.0
      env: build_config=Release
      env: netmoniker=net461
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.0.1
      env: build_config=Debug
      env: netmoniker=net461
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.0.0
      env: build_config=Debug
      env: netmoniker=net461
    - os: linux
      dist: precise
      sudo: required
      mono: 5.0.1
      env: build_config=Debug
      env: netmoniker=net461
    - os: linux
      dist: precise
      sudo: required
      mono: 5.0.0
      env: build_config=Debug
      env: netmoniker=net461
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 5.0.1
      env: build_config=Release
      env: netmoniker=net461
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 5.0.0
      env: build_config=Release
      env: netmoniker=net461
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 5.0.1
      env: build_config=Release
      env: netmoniker=net461
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 5.0.0
      env: build_config=Release
      env: netmoniker=net461
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 5.0.1
      env: build_config=Debug
      env: netmoniker=net461
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 5.0.0
      env: build_config=Debug
      env: netmoniker=net461
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 5.0.1
      env: build_config=Debug
      env: netmoniker=net461
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 5.0.0
      env: build_config=Debug
      env: netmoniker=net461


#before_install:

before_script:
  - ./build.sh -Target Restore

script:
  - ./build.sh -Target Build

after_script:
  - travis_wait 60 ./build.sh -Target AllTests
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait 60 ./build.sh -Target Upload-Coverage; fi