language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: alpha
    - os: linux
      dist: trusty
      sudo: required
      mono: beta
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.2
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.1
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.0
    - os: linux
      dist: precise
      sudo: required
      mono: alpha
    - os: linux
      dist: precise
      sudo: required
      mono: beta
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.2
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.1
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.0


#before_install:
#  - sudo apt-get install nunit-console
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fiopenssl; fi

before_script:
  - "export DISPLAY=:99.0"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start
  - if [ "$DOTNETCORE" == "1" ]; then dotnet restore; fi
  - if [ "$DOTNETCORE" != "1" ]; then nuget restore Computator.NET"$netmoniker".sln; fi
#  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Computator.NET.DataTypes/Computator.NET.DataTypes"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Charting/Computator.NET.Charting"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Core/Computator.NET.Core"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET/Computator.NET"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Tests/Computator.NET.Tests.csproj
  - xbuild /p:Configuration=Release Computator.NET.IntegrationTests/Computator.NET.IntegrationTests.csproj
  - xbuild /p:Configuration=Debug Computator.NET.DataTypes/Computator.NET.DataTypes"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Charting/Computator.NET.Charting"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Core/Computator.NET.Core"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET/Computator.NET"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Tests/Computator.NET.Tests.csproj
  - xbuild /p:Configuration=Debug Computator.NET.IntegrationTests/Computator.NET.IntegrationTests.csproj


after_script:
#  - nunit-console Computator.NET.Tests/bin/Release/Computator.NET.Tests.dll
#  - nunit-console Computator.NET.IntegrationTests/bin/Release/Computator.NET.IntegrationTests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe --labels=All Computator.NET.Tests/bin/Release/Computator.NET.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe --labels=All Computator.NET.IntegrationTests/bin/Release/Computator.NET.IntegrationTests.dll
#  - nunit-console Computator.NET.Tests/bin/Debug/Computator.NET.Tests.dll
#  - nunit-console Computator.NET.IntegrationTests/bin/Debug/Computator.NET.IntegrationTests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe --labels=All Computator.NET.Tests/bin/Debug/Computator.NET.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe --labels=All Computator.NET.IntegrationTests/bin/Debug/Computator.NET.IntegrationTests.dll