language: csharp
solution: Computator.NET.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.2
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.4.2
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.0.0
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 3.12.0
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 3.10.0
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 3.8.0
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 3.2.8
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      mono: 2.10.8
      env: netmoniker=.NET40
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.2
    - os: linux
      dist: precise
      sudo: required
      mono: 4.4.2
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 4.0.0
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 3.12.0
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 3.10.0
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 3.8.0
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 3.2.8
      env: netmoniker=.NET40
    - os: linux
      dist: precise
      sudo: required
      mono: 2.10.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.2
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.4.2
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.0.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 3.12.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 3.10.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 3.8.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 3.2.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 2.10.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode8.2
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode8.2
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 4.6.2
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 4.4.2
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 4.0.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 3.12.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 3.10.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 3.8.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 3.2.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      mono: 2.10.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode7.3
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode7.3
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.2
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.4.2
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.0.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 3.12.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 3.10.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 3.8.0
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 3.2.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 2.10.8
      env: netmoniker=.NET40
    - os: osx
      osx_image: xcode6.4
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode6.4
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1


#before_install:
#  - sudo apt-get install nunit-console

before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "sh -e /etc/init.d/xvfb start"; fi
  - sleep 3 # give xvfb some time to start
  - nuget restore Computator.NET"$netmoniker".sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Computator.NET.DataTypes/Computator.NET.DataTypes"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Core/Computator.NET.Core"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Charting/Computator.NET.Charting"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET/Computator.NET"$netmoniker".csproj
  - xbuild /p:Configuration=Release Computator.NET.Tests/Computator.NET.Tests.csproj
  - xbuild /p:Configuration=Release Computator.NET.IntegrationTests/Computator.NET.IntegrationTests.csproj
  - xbuild /p:Configuration=Debug Computator.NET.DataTypes/Computator.NET.DataTypes"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Core/Computator.NET.Core"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Charting/Computator.NET.Charting"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET/Computator.NET"$netmoniker".csproj
  - xbuild /p:Configuration=Debug Computator.NET.Tests/Computator.NET.Tests.csproj
  - xbuild /p:Configuration=Debug Computator.NET.IntegrationTests/Computator.NET.IntegrationTests.csproj


after_script:
#  - nunit-console Computator.NET.Tests/bin/Release/Computator.NET.Tests.dll
#  - nunit-console Computator.NET.IntegrationTests/bin/Release/Computator.NET.IntegrationTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Computator.NET.Tests/bin/Release/Computator.NET.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Computator.NET.IntegrationTests/bin/Release/Computator.NET.IntegrationTests.dll
#  - nunit-console Computator.NET.Tests/bin/Debug/Computator.NET.Tests.dll
#  - nunit-console Computator.NET.IntegrationTests/bin/Debug/Computator.NET.IntegrationTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Computator.NET.Tests/bin/Debug/Computator.NET.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Computator.NET.IntegrationTests/bin/Debug/Computator.NET.IntegrationTests.dll