language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.2
      env: build_config=Release
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.1
      env: build_config=Release
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.0
      env: build_config=Release
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.2
      env: build_config=Release
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.1
      env: build_config=Release
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.0
      env: build_config=Release
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.2
      env: build_config=Debug
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.1
      env: build_config=Debug
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.6.0
      env: build_config=Debug
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.2
      env: build_config=Debug
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.1
      env: build_config=Debug
    - os: linux
      dist: precise
      sudo: required
      mono: 4.6.0
      env: build_config=Debug
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.2
      env: build_config=Release
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.1
      env: build_config=Release
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.0
      env: build_config=Release
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.2
      env: build_config=Release
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.1
      env: build_config=Release
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.0
      env: build_config=Release
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.2
      env: build_config=Debug
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.1
      env: build_config=Debug
    - os: osx
      osx_image: xcode8.2
      sudo: required
      mono: 4.6.0
      env: build_config=Debug
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.2
      env: build_config=Debug
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.1
      env: build_config=Debug
    - os: osx
      osx_image: xcode6.4
      sudo: required
      mono: 4.6.0
      env: build_config=Debug

#before_install:

before_script:
  - source ./build-mono/restore.sh

script:
  - ./build-mono/build.sh

after_script:
  - ./build-mono/test.sh