version: 2.3.3.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: KEH5rJaqCoWoCV2MhkrMlClj3SVIlB2Eu0YK4mqmhRM+ANEfGiFyROo2RWHkJXQz
  matrix:
  - netmoniker: net461
  - netmoniker: net40

image:
- Visual Studio 2017

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: '**\*SharedAssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: "{version}β"

before_build:
  - build.cmd -Target Restore

build_script:
  - build.cmd -Target Build

#test_script:
#  - build.cmd -Target AllTests

after_test:
  - build.cmd -Target Upload-Coverage

after_build:
  - build.cmd -Target Build-Installer
  - build.cmd -Target Build-Uwp

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - pawel.troka@outlook.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true